/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ronildo.facanha (https://sketchfab.com/ronildo.facanha)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-naruto-with-rig-and-running-animation-db14fc3de5b34b738e49ec3cdb83770a
Title: Low Poly Naruto with Rig and Running Animation
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import scene from "../assets/3d/naruto.glb";

export function Naruto(currentAnimation, ...props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.log(actions);
    actions["Armature|mixamo.com|Layer0"].play();
  }, [actions, currentAnimation]);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[1.2, -1.7, 0]} // Mover a la derecha y hacia abajo
      rotation={[0, -Math.PI / 4, 0]} // Rotación para verlo de perfil
      scale={[1.3, 1.3, 1.3]}
    >
      {" "}
      // Ajusta la escala si es necesario
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.035}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Armature_72"
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
              >
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials["nrt_tex02_png-material.001"]}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.Line}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials["nrt_tex02_png-material.001"]}
                    skeleton={nodes.Object_10.skeleton}
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials.Line}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    material={materials["nrt_tex02_png-material.001"]}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <skinnedMesh
                    name="Object_14"
                    geometry={nodes.Object_14.geometry}
                    material={materials.Line}
                    skeleton={nodes.Object_14.skeleton}
                  />
                  <skinnedMesh
                    name="Object_16"
                    geometry={nodes.Object_16.geometry}
                    material={materials["nrt_tex03_png-material.001"]}
                    skeleton={nodes.Object_16.skeleton}
                  />
                  <skinnedMesh
                    name="Object_17"
                    geometry={nodes.Object_17.geometry}
                    material={materials.Line}
                    skeleton={nodes.Object_17.skeleton}
                  />
                  <skinnedMesh
                    name="Object_19"
                    geometry={nodes.Object_19.geometry}
                    material={materials["nrt_tex01_png-material.001"]}
                    skeleton={nodes.Object_19.skeleton}
                  />
                  <skinnedMesh
                    name="Object_20"
                    geometry={nodes.Object_20.geometry}
                    material={materials.Line}
                    skeleton={nodes.Object_20.skeleton}
                  />
                  <skinnedMesh
                    name="Object_22"
                    geometry={nodes.Object_22.geometry}
                    material={materials["nrt_eye_png-material.001"]}
                    skeleton={nodes.Object_22.skeleton}
                  />
                  <skinnedMesh
                    name="Object_24"
                    geometry={nodes.Object_24.geometry}
                    material={materials["makimono_01_png-material.001"]}
                    skeleton={nodes.Object_24.skeleton}
                  />
                  <skinnedMesh
                    name="Object_25"
                    geometry={nodes.Object_25.geometry}
                    material={materials.Line}
                    skeleton={nodes.Object_25.skeleton}
                  />
                  <group name="_008_mesh34001_65" />
                  <group name="_009_mesh32001_66" />
                  <group name="_012_mesh16001_67" />
                  <group name="_013_mesh16001_68" />
                  <group name="_014_mesh16001_69" />
                  <group name="_015_mesh16001_70" />
                  <group name="_016_mesh16001_71" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

export default Naruto;
